import Link from "next/link";
import { Award, CheckCircle2, Cpu, Github, ShieldCheck } from "lucide-react";
import { getSiteConfig } from "@/lib/config";

export default async function ExamplePage() {
  const cfg = await getSiteConfig();
  return (
    <div className="mx-auto max-w-4xl px-4 py-12 sm:px-6">
      <p className="text-xs font-medium uppercase tracking-wide text-zinc-500">Example portfolio · demo</p>
      <h1 className="mt-2 text-3xl font-bold tracking-tight text-zinc-900">Priya Nair</h1>
      <p className="mt-1 text-zinc-600">Becoming an AI engineer · 8 weeks in</p>

      <div className="mt-2 inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-semibold text-white" style={{ backgroundColor: cfg.brand.primaryColor }}>
        <ShieldCheck className="h-3.5 w-3.5" /> Verified on {cfg.brand.name}
      </div>

      <section className="mt-10 card">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-zinc-500">Path progress</h2>
        <h3 className="mt-2 text-xl font-semibold text-zinc-900">AI Engineer · 12 weeks</h3>
        <p className="mt-1 text-zinc-600">From Python basics to deploying a RAG-powered chatbot.</p>
        <p className="mt-3 text-sm text-zinc-500">
          21 / 36 milestones complete · 4 phases ·{" "}
          <span className="inline-flex items-center gap-1">
            <Cpu className="h-3.5 w-3.5" /> generated by gemma-3-27b-it
          </span>
        </p>
      </section>

      <section className="mt-8">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-zinc-500">Verified projects</h2>
        <div className="mt-3 space-y-4">
          <Project
            title="Course notes RAG bot"
            repo="priya/notes-rag"
            score={0.86}
            skills={["python", "langchain", "retrieval", "fastapi", "chromadb"]}
            strengths={[
              "Clean separation of retrieval, chunking, and inference layers",
              "Includes evaluation set + benchmark notebook",
              "Original chunking heuristics, not a tutorial clone",
            ]}
            models={["gemma-3-27b-it", "gemma-3-12b-it"]}
          />
          <Project
            title="Bird species classifier (CNN)"
            repo="priya/birdspot"
            score={0.78}
            skills={["pytorch", "computer-vision", "data-augmentation"]}
            strengths={[
              "Trained from scratch on a 5k-sample subset",
              "Custom data augmentation pipeline with verified accuracy gain",
            ]}
            models={["gemma-3-27b-it"]}
          />
        </div>
      </section>

      <section className="mt-8">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-zinc-500">Credentials</h2>
        <div className="mt-3 grid gap-3 sm:grid-cols-2">
          <Credential title="Course notes RAG bot" skills={["python", "langchain"]} />
          <Credential title="Bird species classifier" skills={["pytorch", "cv"]} />
          <Credential title="Python deep-dive (89% quiz mastery)" skills={["python"]} type="quiz_mastery" />
          <Credential title="ML fundamentals milestone" skills={["ml"]} type="milestone" />
        </div>
      </section>

      <div className="mt-12 rounded-xl border border-zinc-200 bg-zinc-50 p-6 text-center">
        <p className="text-sm text-zinc-600">
          This is an example.{" "}
          <Link href="/onboarding" className="font-semibold text-zinc-900 underline">
            Start your own path
          </Link>
        </p>
      </div>
    </div>
  );
}

function Project({
  title,
  repo,
  score,
  skills,
  strengths,
  models,
}: {
  title: string;
  repo: string;
  score: number;
  skills: string[];
  strengths: string[];
  models: string[];
}) {
  return (
    <div className="card">
      <div className="flex items-center justify-between">
        <h3 className="font-semibold text-zinc-900">{title}</h3>
        <span className="text-sm font-medium text-emerald-700">{Math.round(score * 100)}%</span>
      </div>
      <p className="mt-1 inline-flex items-center gap-1 text-sm text-zinc-600">
        <Github className="h-3.5 w-3.5" /> {repo}
      </p>
      <div className="mt-2 flex flex-wrap gap-1.5">
        {skills.map((s) => (
          <span key={s} className="badge-neutral">
            {s}
          </span>
        ))}
      </div>
      <ul className="mt-3 space-y-1 text-sm text-zinc-600">
        {strengths.map((s, i) => (
          <li key={i}>
            <CheckCircle2 className="mr-1 inline h-3.5 w-3.5 text-emerald-600" />
            {s}
          </li>
        ))}
      </ul>
      <p className="mt-3 text-xs text-zinc-400">
        Evaluated by:{" "}
        {models.map((m, i) => (
          <span key={i} className="font-mono">
            {i > 0 ? ", " : ""}
            {m}
          </span>
        ))}
      </p>
    </div>
  );
}

function Credential({
  title,
  skills,
  type = "project",
}: {
  title: string;
  skills: string[];
  type?: string;
}) {
  return (
    <div className="card !p-4">
      <div className="flex items-start justify-between">
        <div>
          <p className="text-xs font-medium uppercase tracking-wide text-zinc-500">{type}</p>
          <p className="mt-1 font-semibold text-zinc-900">{title}</p>
        </div>
        <Award className="h-5 w-5 text-amber-500" />
      </div>
      <div className="mt-2 flex flex-wrap gap-1">
        {skills.map((s) => (
          <span key={s} className="badge-neutral">
            {s}
          </span>
        ))}
      </div>
    </div>
  );
}
