"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useSession, signIn } from "next-auth/react";
import { ArrowRight, CheckCircle2, Circle, Cpu, Loader2, Sparkles, Trophy } from "lucide-react";
import { getGuestToken, getGuestMeta } from "@/lib/guest";
import { proxyFetch } from "@/lib/clientFetch";

type Resource = {
  title: string;
  url: string;
  type: string;
  expectedMinutes: number;
  status: "pending" | "in_progress" | "done" | "skipped";
};

type Milestone = {
  week: number;
  topic: string;
  summary: string;
  deliverable: string;
  resources: Resource[];
  status: "pending" | "in_progress" | "done";
};

type ProjectSpec = {
  title: string;
  description: string;
  difficulty: "easy" | "medium" | "hard";
  expectedHours: number;
  skills: string[];
  isNorthStar: boolean;
};

type Phase = {
  name: string;
  description: string;
  weeks: number[];
  milestones: Milestone[];
  projects: ProjectSpec[];
};

type Path = {
  _id: string;
  goal: string;
  targetRole: string;
  timelineWeeks: number;
  summary: string;
  stretchGoalWarning?: string;
  phases: Phase[];
  generatedBy?: { provider: string; model: string };
};

export default function DashboardPage() {
  const { status, data: session } = useSession();
  const [path, setPath] = useState<Path | null>(null);
  const [loading, setLoading] = useState(true);
  const [hasGuest, setHasGuest] = useState(false);

  useEffect(() => {
    setHasGuest(!!getGuestToken());
  }, []);

  useEffect(() => {
    if (status === "unauthenticated" && !hasGuest) return;
    proxyFetch("/paths/active")
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => setPath(data))
      .finally(() => setLoading(false));
  }, [status, hasGuest]);

  if (status === "unauthenticated" && !hasGuest) {
    return (
      <div className="mx-auto max-w-md px-4 py-20 text-center">
        <h1 className="text-2xl font-bold text-zinc-900">Please sign in</h1>
        <button onClick={() => signIn("github")} className="btn-primary mt-6">
          Sign in with GitHub
        </button>
      </div>
    );
  }

  const guestMeta = getGuestMeta();
  const isGuest = !session?.backendToken && !!guestMeta;

  if (loading) {
    return (
      <div className="mx-auto max-w-3xl px-4 py-20 text-center text-zinc-500">
        <Loader2 className="mx-auto h-6 w-6 animate-spin" />
      </div>
    );
  }

  if (!path) {
    return (
      <div className="mx-auto max-w-2xl px-4 py-16 text-center">
        <h1 className="text-2xl font-bold text-zinc-900">No active path yet</h1>
        <p className="mt-2 text-zinc-600">Tell us your goal and Gemma 4 will build your 12-week path.</p>
        <Link href="/onboarding" className="btn-primary mt-6 inline-flex">
          Generate my path <ArrowRight className="h-4 w-4" />
        </Link>
      </div>
    );
  }

  const total = path.phases.reduce((acc, p) => acc + p.milestones.length, 0);
  const done = path.phases.reduce(
    (acc, p) => acc + p.milestones.filter((m) => m.status === "done").length,
    0,
  );
  const pct = total > 0 ? Math.round((done / total) * 100) : 0;

  async function markDone(phaseIndex: number, milestoneIndex: number) {
    const res = await proxyFetch(`/paths/${path!._id}/milestone/done`, {
      method: "POST",
      body: JSON.stringify({ phaseIndex, milestoneIndex }),
    });
    if (res.ok) setPath(await res.json());
  }

  return (
    <div className="mx-auto max-w-4xl px-4 py-10 sm:px-6">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <p className="text-sm font-medium text-zinc-500">Your path to</p>
          <h1 className="text-3xl font-bold tracking-tight text-zinc-900">{path.targetRole || "your goal"}</h1>
          <p className="mt-1 text-zinc-600">{path.summary}</p>
        </div>
        <Link href="/projects/new" className="btn-primary">
          Submit a project <ArrowRight className="h-4 w-4" />
        </Link>
      </div>

      <div className="mt-6 flex flex-wrap items-center gap-4">
        <div className="flex-1 min-w-[200px]">
          <div className="h-2 w-full rounded-full bg-zinc-200">
            <div
              className="h-2 rounded-full transition-all"
              style={{ width: `${pct}%`, backgroundColor: "var(--brand-primary)" }}
            />
          </div>
          <p className="mt-2 text-sm text-zinc-600">
            {done} of {total} milestones complete · {pct}%
          </p>
        </div>
        {path.generatedBy?.model ? (
          <div className="badge-neutral">
            <Cpu className="h-3 w-3" /> Generated by {path.generatedBy.model}
          </div>
        ) : null}
      </div>

      {path.stretchGoalWarning ? (
        <div className="mt-6 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">
          <strong>Heads up:</strong> {path.stretchGoalWarning}
        </div>
      ) : null}

      <div className="mt-10 space-y-10">
        {path.phases.map((phase, pi) => (
          <PhaseCard
            key={pi}
            phase={phase}
            index={pi}
            onMarkDone={(mi) => markDone(pi, mi)}
          />
        ))}
      </div>

      {session?.user?.handle ? (
        <div className="mt-10 flex justify-end">
          <Link href={`/u/${session.user.handle}`} className="btn-ghost text-sm">
            <Trophy className="h-4 w-4" /> View your public portfolio
          </Link>
        </div>
      ) : isGuest && guestMeta ? (
        <div className="mt-10 flex justify-end">
          <Link href={`/u/${guestMeta.handle}`} className="btn-ghost text-sm">
            <Trophy className="h-4 w-4" /> View your guest portfolio
          </Link>
        </div>
      ) : null}
    </div>
  );
}

function PhaseCard({
  phase,
  index,
  onMarkDone,
}: {
  phase: Phase;
  index: number;
  onMarkDone: (milestoneIndex: number) => void;
}) {
  return (
    <section>
      <div className="flex items-baseline justify-between">
        <h2 className="text-xl font-semibold text-zinc-900">
          Phase {index + 1}: {phase.name}
        </h2>
        <p className="text-sm text-zinc-500">Weeks {phase.weeks.join(", ")}</p>
      </div>
      {phase.description ? <p className="mt-1 text-sm text-zinc-600">{phase.description}</p> : null}

      <div className="mt-4 space-y-3">
        {phase.milestones.map((m, mi) => (
          <div
            key={mi}
            className={`rounded-lg border p-4 transition ${
              m.status === "done"
                ? "border-emerald-200 bg-emerald-50/40"
                : "border-zinc-200 bg-white"
            }`}
          >
            <div className="flex items-start justify-between gap-3">
              <button
                onClick={() => m.status !== "done" && onMarkDone(mi)}
                className="mt-0.5 flex-shrink-0"
                title={m.status === "done" ? "Done" : "Mark as done"}
              >
                {m.status === "done" ? (
                  <CheckCircle2 className="h-5 w-5 text-emerald-600" />
                ) : (
                  <Circle className="h-5 w-5 text-zinc-400" />
                )}
              </button>
              <div className="flex-1">
                <p className="text-xs font-medium text-zinc-500">Week {m.week}</p>
                <h3 className="font-semibold text-zinc-900">{m.topic}</h3>
                {m.summary ? <p className="mt-1 text-sm text-zinc-600">{m.summary}</p> : null}
                {m.deliverable ? (
                  <p className="mt-2 text-sm">
                    <span className="font-medium text-zinc-700">Deliverable:</span>{" "}
                    <span className="text-zinc-600">{m.deliverable}</span>
                  </p>
                ) : null}
                {m.resources?.length ? (
                  <ul className="mt-3 space-y-1">
                    {m.resources.map((r, ri) => (
                      <li key={ri} className="text-sm">
                        <a
                          href={r.url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-zinc-700 underline hover:text-zinc-900"
                        >
                          {r.title}
                        </a>
                        <span className="ml-2 text-xs text-zinc-500">
                          {r.type} · {r.expectedMinutes}m
                        </span>
                      </li>
                    ))}
                  </ul>
                ) : null}
              </div>
            </div>
          </div>
        ))}
      </div>

      {phase.projects?.length ? (
        <div className="mt-4">
          <p className="mb-2 text-sm font-medium text-zinc-700">Projects in this phase</p>
          <div className="grid gap-3 sm:grid-cols-2">
            {phase.projects.map((p, i) => (
              <div
                key={i}
                className={`card !p-4 ${p.isNorthStar ? "border-amber-300 bg-amber-50/30" : ""}`}
              >
                <div className="flex items-center gap-2">
                  {p.isNorthStar ? <Sparkles className="h-4 w-4 text-amber-600" /> : null}
                  <h4 className="font-semibold text-zinc-900">{p.title}</h4>
                </div>
                <p className="mt-1 text-sm text-zinc-600">{p.description}</p>
                <div className="mt-2 flex flex-wrap gap-1.5">
                  <span className="badge-neutral">{p.difficulty}</span>
                  <span className="badge-neutral">{p.expectedHours}h</span>
                  {p.isNorthStar ? <span className="badge-brand">North star</span> : null}
                </div>
              </div>
            ))}
          </div>
        </div>
      ) : null}
    </section>
  );
}
